### ISSUE TITLE
Why must the IMAPStore.getFolder method be executed synchronously, and synchronized can be removed?

### ISSUE THREAD

**Issue by jiao-sir** [jakartaee/mail-api#514]
### My server has multiple users using the mailbox application. This method will block every time the mailbox is synchronized. Can they execute this method at the same time?
![image](https://user-images.githubusercontent.com/44576216/106224552-81229400-621e-11eb-8d09-5dc98b01a89a.png)

**Comment by jiao-sir** [comment]
I need to use multiple threads to accept imap mail, how should I achieve it?

**Comment by jmehrens** [comment]
Sessions can be shared across threads but Stores and Transports should be local to a thread. Keep stores and folders local to same thread and there will be no contention.
