### ISSUE TITLE
Don't throw exception on unknown 2yz recipient error

### ISSUE THREAD

**Issue by cjnewman** [jakartaee/mail-api#577]
**Describe the bug**
Jakarta mail presently throws an exception when the server response to RCPT TO is an unknown 2xx response. The standard states: https://datatracker.ietf.org/doc/html/rfc5321#section-4.3.2
   ... Since some servers may generate other
   replies under special circumstances, and to allow for future
   extension, SMTP clients SHOULD, when possible, interpret only the
   first digit of the reply and MUST be prepared to deal with
   unrecognized reply codes by interpreting the first digit only.

The standard states that servers SHOULD NOT send such responses, but unfortunately an engineer on OCI Email Delivery deployed and documented a new three digit code (254) which became a documented interface here: https://docs.oracle.com/en-us/iaas/Content/Email/Concepts/troubleshooting.htm
and cloud stability rules require one year advance notice prior to changing a documented interface so once a plan to fix this is started, it will still take a year before it's fixed on the server side.

So this is a request to have Jakarta mail comply with RFC 5321 "MUST be prepared to deal with unrecognized reply codes by interpreting the first digit only." by treating any 2yz RCPT TO response as a success.

The present workaround is complicated and described here: 
https://docs.oracle.com/en-us/iaas/Content/knownissues.htm#javamail

**To Reproduce**
1. Send email with two recipients to a server that returns an unknown 2xx response code to one of those recipients (e.g., OCI Email Delivery with a suppressed recipient).
2. Jakarta mail API raises an exception.

Also described here: https://docs.oracle.com/en-us/iaas/Content/knownissues.htm#javamail

**Expected behavior**
Jakarta mail API should not raise an exception in this case; the unknown 2yz response should be treated the same as 250 since in SMTP theory of reply codes (section 4.2.1), a 2yz reply is "Positive Completion reply".

**Screenshots**

**Desktop (please complete the following information):**
 - All

**Smartphone (please complete the following information):**
 - All

**Mail server:**
 - Protocol being used: SMTP Submission (RFC 6409 + RFC 5321)
 - Vendor/product: Oracle Cloud Infrastructure Email Delivery
 - Mail service URL: https://docs.oracle.com/en-us/iaas/Content/Email/Concepts/overview.htm

**Additional context**

**Comment by jmehrens** [comment]
@lukasj only mail-tck and mail-spec show up as options for an issue transfer.
