### ISSUE TITLE
mail.smtp.ssl.trust creates a new SocketFactory

### ISSUE THREAD

**Issue by demarco88** [jakartaee/mail-api#609]
Hi.
The documentation of mail.smtp.ssl.trust said:
"If set, **and a socket factory hasn't been specified,** enables use of a [MailSSLSocketFactory](https://javaee.github.io/javamail/docs/api/com/sun/mail/util/MailSSLSocketFactory.html). If set to "*", all hosts are trusted. If set to a whitespace separated list of hosts, those hosts are trusted. Otherwise, trust depends on the certificate the server presents."
We set a own "mail.smtp.socketFactory" with a truststore and keystore but the MailSSLSocketFactory is created anyway if mail.smtp.ssl.trust is specified.
thx

**Comment by lukasj** [comment]
moved to https://github.com/eclipse-ee4j/angus-mail/issues/65
