### ISSUE TITLE
I am developing an OpenHarmony application with JavaScript language which used your library, will your library support OpenHarmony platform by JavaScript language? if so, I want to contribute to the OpenHarmony build of this library. Expecte foe your reply!

### ISSUE THREAD

**Issue by DoraCoder** [jakartaee/mail-api#615]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jmehrens** [comment]
Duplicate of https://github.com/jakartaee/mail-api/issues/608
