### ISSUE TITLE
TCK Challenge: TCK should not require JPMS module-info.class

### ISSUE THREAD

**Issue by brideck** [jakartaee/mail-api#625]
**Challenged Tests:**
[build.xml](https://github.com/eclipse-ee4j/mail-tck/blob/master/build.xml#L207)

**TCK Version:**
Jakarta Mail 2.1.0

**Tested Implementation:**
Open Liberty

**Description:**
Per [section 13.3 of the EE 10 specification](https://jakarta.ee/specifications/platform/10/jakarta-platform-spec-10.0.html#java-platform-module-system-jpms), "Vendors are free to create their own API jars that pass the signature tests, but include no JPMS module-info.class files or JPMS module-info.class files with different or conflicting contents."  However, the entire automation of this TCK is requiring that the API jar being tested contain a module-info.class file.

Open Liberty does not provide API jars containing a module-info.class and as such is unable to run this TCK as it is currently written.  Attempts to do so fail with the following:
```
[javatest.batch] java.lang.module.FindException: Unable to derive module descriptor for /jakarta/vi/wlp/dev/api/spec/io.openliberty.jakarta.mail.2.1_1.0.70.jar
[javatest.batch] Caused by: java.lang.IllegalArgumentException: io.openliberty.jakarta.mail.2.1.1.0.70: Invalid module name: '2' is not a Java identifier
[javatest.batch] Java Result: 1
```

Note that this is essentially the same thing as [this challenge](https://github.com/eclipse-ee4j/jaf/issues/98) opened against Activation, only this TCK does not appear to contain any specific tests checking the API jar's module name.  Whatever happens to that challenge, the same thing should happen here.

**Comment by Emily-Jiang** [comment]
Can one of the committers add the label `Challenge`?

**Comment by lukasj** [comment]
resolution:

* for the platform runs, new test configuration config file (`ts-platform.jte`) gets created
* instructions in the user guide get updated with section how to execute the TCK for the EE platform
* user guide explicitly mentions that certification for the EE platform does not imply certification for SE environment

**Comment by brideck** [comment]
In order to achieve certification for EE 10, Open Liberty is currently working around this issue in our TCK automation by adding the `module-info.class` from `jakarta.mail:jakarta.mail-api:2.1.0` to our shipped API jar (`io.openliberty.jakarta.mail.2.1_<version>.jar`).

Could we please get formal approval of this approach for certification purposes?  If approved, I will reference this challenge issue from our certification comaptibility request.  We will, of course, change to using the updated TCK as it becomes available.

**Comment by lukasj** [comment]
How do you run this TCK? Running `ant run` as is documented in the TCK user guide does not lead to the reported exception on my end (I manually removed module descriptors from the API jars I use; the exec command also does not use the module path argument).

**Comment by brideck** [comment]
> How do you run this TCK? Running `ant run` as is documented in the TCK user guide does not lead to the reported exception on my end (I manually removed module descriptors from the API jars I use; the exec command also does not use the module path argument).

I do use `ant run`, which does indeed include a module path. All roads in the build.xml lead to this definition:
```
    <presetdef name="javatest">
        <java classname="com.sun.javatest.tool.Main"
              failonerror="${failOnError}" fork="yes" classpath="${run.class.path}" modulepath="${module.path}">
```

Note the `modulepath=` at the end there.

The error that I get, as stated in the initial challenge, is a weird versioning one, perhaps specific to Open Liberty's naming/versioning conventions. Simply removing the module-info from jakarta.mail-api.jar may not actually be enough to reproduce it.

**Comment by lukasj** [comment]
https://github.com/jakartaee/mail-tck/blob/master/build.xml#L146 says javatest.batch, I think. What do I have to do, to let it go through javatest instead? Sorry, I’m probably missing something obvious somewhere

**Comment by brideck** [comment]
> https://github.com/jakartaee/mail-tck/blob/master/build.xml#L146 says javatest.batch, I think. What do I have to do, to let it go through javatest instead? Sorry, I’m probably missing something obvious somewhere

javatest.batch just calls javatest, as seen here: https://github.com/jakartaee/mail-tck/blob/master/build.xml#L223

**Comment by lukasj** [comment]
finally reproduced the problem. It wasn't cleat to me _when_ exactly the error appears - whether during the test runs OR during the start up of the tests. The latter is the case here, so under the hood, the cause and fix are going to be different from similar issue in activation tck
