### ISSUE TITLE
java.lang.NoClassDefFoundError: com/sun/activation/registries/LogSupport critical issue

### ISSUE THREAD

**Issue by 81300988** [jakartaee/mail-api#627]
In our project we use javax.mail 1.5.2, everything is ok util yesterday(19/10/2022) when buiding jenkins we can not download **activation-1.1.jar** file, but there is just warning (warning log) and the pipeline is still successful. After that we the application run on production and the app is crash with the error (error log).
But in the few weeks ago we still can download all package of javax.mail 1.5.2 without any issue (The builds)

**Warning log:** 
Downloaded from central: https://repo.maven.apache.org/maven2/io/grpc/grpc-api/maven-metadata.xml (2.8 kB at 2.5 kB/s)
#16 4.649 [WARNING] The POM for com.sun.mail:javax.mail:jar:1.5.2 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details

**Error log:** 
java.lang.NoClassDefFoundError: com/sun/activation/registries/LogSupport
	at javax.activation.MailcapCommandMap.<init>(MailcapCommandMap.java:149)
	at javax.activation.CommandMap.getDefaultCommandMap(CommandMap.java:55)
	at javax.activation.DataHandler.getCommandMap(DataHandler.java:137)
	at javax.activation.DataHandler.getDataContentHandler(DataHandler.java:599)
	at javax.activation.DataHandler.writeTo(DataHandler.java:299)
	at javax.mail.internet.MimeUtility.getEncoding(MimeUtility.java:323)
	at javax.mail.internet.MimeBodyPart.updateHeaders(MimeBodyPart.java:1495)
	at javax.mail.internet.MimeMessage.updateHeaders(MimeMessage.java:2190)
	at javax.mail.internet.MimeMessage.saveChanges(MimeMessage.java:2151)
	at javax.mail.Transport.send(Transport.java:123)

**The builds:**
   Few weeks ago:
        
![image](https://user-images.githubusercontent.com/29403358/196845586-2b86a69c-668c-42a3-bda2-71d65b937aa4.png)

   Now:
      
![image](https://user-images.githubusercontent.com/29403358/196845624-e010c002-7666-4b1b-b0bb-d9df5c2fc01d.png)

**To Reproduce**
1. Use javax.mail version 1.5.2
    <dependency>
            <groupId>com.sun.mail</groupId>
            <artifactId>javax.mail</artifactId>
            <version>1.5.2</version>
     </dependency>
     
2. Build and run application
3. Send mail

**Expected behavior**
Can completely download javax.mail 1.5.2 included activation-1.1.jar

**Temporary solution**
Update the javax.mail version to 1.6.0

**Important**
This is very critical issue, because we do not know when our application crash on production env even we upgrade the verion to 1.6.0 we can not sure this issue will not happen in future

**Comment by jbescos** [comment]
What maven repository do you use to fetch javax.mail:1.5.2?

I only see the latest is 1.5.0-b01 here: https://mvnrepository.com/artifact/javax.mail/mail

**Comment by jbescos** [comment]
We don't support that javax anymore, but you can add in your pom the activation 1.1 and your problem will be solved:
```
<dependency>
    <groupId>javax.activation</groupId>
    <artifactId>activation</artifactId>
    <version>1.1</version>
</dependency>

```

Note that [mail](https://mvnrepository.com/artifact/com.sun.mail/javax.mail/1.6.0) does not include activation either in the mail jar file.

In case you want to move to 1.6.0, here is the list of changes:
https://javaee.github.io/javamail/docs/JavaMail-1.6-changes.txt

**Comment by 81300988** [comment]
@jbescos I have sovled the problem, thank for your support.

**Comment by jbescos** [comment]
Ok, we can close this
