### ISSUE TITLE
Use OSGi service loader mediator instead of osgi resource locator

### ISSUE THREAD

**Issue by mnlipp** [jakartaee/mail-api#630]
To separate the API and the implementation, the service loader pattern is used. This perfectly well suited mechanism is known to have problems in OSGi environments.

An attempt has been made in the jakarta mail api implementation to solve the problems with org.glassfish.hk2.osgi-resource-locator, which requires lots of special coding.

The "service loader and OSGi" problem has actually successfully been addressed before by http://docs.osgi.org/specification/osgi.enterprise/7.0.0/service.loader.html with the reference implementation (with an easier to read description) [SPI Fly](https://aries.apache.org/documentation/modules/spi-fly.html). What it boils down to is that instead of having to maintain the complicated code, you can simply use the service locator after adding some statements to MANIFEST.MF.

While this is not a runtime bug, because you can use Jakarta mail api in an OSGi environment (once you have found out that you need to include the hk2 jar and once https://github.com/eclipse-ee4j/mail/issues/629 will be fixed), I think it is a bug with respect to the design.

**Comment by mnlipp** [comment]
Having found the usage of hk2 to be implemented [only partially](https://github.com/eclipse-ee4j/mail/issues/629#issuecomment-1287850248), I have patched the `MANIFEST.MF` files of the jars as required for the use of the service loader mediator. I did it manually, as I don't know which build system is used. The required headers are:

In `jakarta.mail-api`:
```properties
Require-Capability: osgi.extender;filter:="(osgi.extender=osgi.servicelo
 ader.processor)";resolution:=optional,osgi.ee;filter:="(&(osgi.ee=JavaS
 E)(version=1.8))"
```

In `angus-core`:
```properties
Provide-Capability: osgi.serviceloader;osgi.serviceloader="jakarta.mail.
 util.StreamProvider"
Require-Capability: osgi.extender;filter:="(osgi.extender=osgi.servicelo
 ader.registrar)",osgi.extender;filter:="(osgi.extender=osgi.serviceload
 er.processor)";resolution:=optional,osgi.ee;filter:="(&(osgi.ee=JavaSE)
 (version=1.8))"
```

And in `imap` (using this as an example):
```properties
Provide-Capability: osgi.serviceloader;osgi.serviceloader="jakarta.mail.
 Provider"
Require-Capability: osgi.extender;filter:="(osgi.extender=osgi.servicelo
 ader.registrar)",osgi.ee;filter:="(&(osgi.ee=JavaSE)(version=1.8))"
```

**Comment by jbescos** [comment]
Thank you for the PR.

The solution looks nice, as it very easily deal with OSGi.

I am curious to know adding some depenencies it is able to modify the MANIFEST.MF.. I guess maven-bundle-plugin:5.1.1:manifest is detecting these dependencies and it is delegating on them.

The only thing that I don't like is that if you decmpkile Session or StreamProvider, you are going to find the ServiceConsumer annotation. As this is only needed to generate the manfest, it looks it is out of scope to find it in the generated jar.

Ideally there should be a plugin to deal with the manifest. Something like this:

```
<plugin>
	<groupId>org.apache.maven.plugins</groupId>
	<artifactId>maven-osgi-plugin</artifactId>
	<configuration>
		<jakarta.mail.util.StreamProvider>jakarta.mail.Provider</jakarta.mail.util.StreamProvider>
		<jakarta.mail.util.StreamProvider>jakarta.mail.util.StreamProvider</jakarta.mail.util.StreamProvider>
	</configuration>
</plugin>
```

I bring the attention of @lukasj. He has been dealing with OSGi issues more time than me (in other words, he knows more than me :) )

**Comment by mnlipp** [comment]
> Ideally there should be a plugin to deal with the manifest. 

You don't need an extra plugin. You can simply add this information using the Felix maven bundle plugin which is already in pom.xml with instructions `<Provide-Capability>` and `<Require-Capability>` (that's doing it "manually", see https://github.com/jakartaee/mail-api/issues/630#issuecomment-1287852918). In general, the manual approach is considered a bit more difficult to maintain, but once it's there, it rarely changes (only if you add another loaded service).

If it helps, I can provide another PR with the pom.xml based solution.

**Comment by jbescos** [comment]
> > Ideally there should be a plugin to deal with the manifest.
> 
> You don't need an extra plugin. You can simply add this information using the Felix maven bundle plugin which is already in pom.xml with instructions `<Provide-Capability>` and `<Require-Capability>` (that's doing it "manually", see [#630 (comment)](https://github.com/jakartaee/mail-api/issues/630#issuecomment-1287852918)). In general, the manual approach is considered a bit more difficult to maintain, but once it's there, it rarely changes (only if you add another loaded service).
> 
> If it helps, I can provide another PR with the pom.xml based solution.

In my opinion that new PR will be better. Also because there is a process to approve new dependencies.
