### ISSUE TITLE
The hk2 service loader is not used everywhere (where necessary)

### ISSUE THREAD

**Issue by mnlipp** [jakartaee/mail-api#635]
**Describe the bug**

Currently, the hk2 service locator is used in [FactoryFinder](https://github.com/jakartaee/mail-api/blob/82dae3a682f8b8a75dc426c28c458ffbcc78014f/api/src/main/java/jakarta/mail/util/FactoryFinder.java#L89-L114) only. Session.java uses the ServiceLoader [without the hk2 "wrapper"](https://github.com/eclipse-ee4j/mail/blob/82dae3a682f8b8a75dc426c28c458ffbcc78014f/api/src/main/java/jakarta/mail/Session.java#L984) and therefore fails to load the providers in an OSGi environment.

**Comment by jbescos** [comment]
@mnlipp this was merged: https://github.com/jakartaee/mail-api/pull/633

Can we close this?

**Comment by mnlipp** [comment]
> Can we close this?

No. #633 was about introducing the OSGi service mediator. Now, if you don't have this in place, the fallback is to use the hk2 service locator. Hk2 requires special coding for looking up the services. This special coding is currently only provided in FactoryFinder. It's missing in Session.java. Therefore providers are not found in an OSGi environment.
