### ISSUE TITLE
java.lang.ClassNotFoundException: Didn't find class "java.util.Base64"

### ISSUE THREAD

**Issue by erictamhk** [jakartaee/mail-api#690]
**Describe the bug**
when using android 7, API 23, got this error

dependencies
    implementation 'org.eclipse.angus:jakarta.mail:2.0.1'
    implementation 'org.eclipse.angus:angus-activation:2.0.1'
    implementation 'jakarta.activation:jakarta.activation-api:2.1.2'

Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Ljava/util/Base64;
        at org.eclipse.angus.mail.smtp.SMTPTransport$LoginAuthenticator.doAuth(SMTPTransport.java:1010)
        at org.eclipse.angus.mail.smtp.SMTPTransport$Authenticator.authenticate(SMTPTransport.java:955)
        at org.eclipse.angus.mail.smtp.SMTPTransport.authenticate(SMTPTransport.java:889)
        at org.eclipse.angus.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:793)

**Comment by jmehrens** [comment]
I would think that we can switch to use MimeUtility.encode with ByteArrayOutputStream to replace the use of Base64.  If I recall correctly there are some differences in how some characters are handled.

**Comment by jmehrens** [comment]
Per [Meet Google Play's target API level requirement](https://developer.android.com/google/play/requirements/target-sdk):

> Starting on August 31, 2023:
>
>    New apps must target Android 13 (API level 33) or higher; except for [Wear OS](https://developer.android.com/wear) apps, which must target a version between Android 11 (API level 30) and Android 13 (API level 33), inclusive.
>
>  App updates must target Android 13 or higher and adjust for behavioral changes in Android 13; except for Wear OS apps, which must target Android 11.
>
>Permanently private apps—which are restricted to users in a specific organization and are intended for internal distribution only—aren't required to meet the target API level requirements.

[snip]

>...Furthermore, as of Android 10 (API level 29), users [see a warning](https://developer.android.com/about/versions/10/behavior-changes-all#low-target-sdk-warnings) when they start an app for the first time if the app targets Android 5.1 (API level 22) or lower.

Per [Which Java APIs can I use in my Java or Kotlin source code?](https://developer.android.com/build/jdks) the API level 32 and API level 33 are versions that support Java 11 source syntax.  API level 34 supports Java 17 source syntax. 

Per [Jakarta EE Platform 10](https://jakarta.ee/specifications/platform/10/):
>Minimum Java SE Version
>Java SE 11 or higher

The [Android API Levels](https://apilevels.com/) site shows the usage of devices.


Given that information we should close this ticket as will not fix and create new ticket to move the minimum API version for JakartaMail and Angus Mail to API 33 as that would allow us to stop building for JDK 8.  Moving to that API version 26 or greater will give access to `java.lang.invoke`, `java.util.Base64`, and `java.time`.  If we want to still target JDK 8 then we should require API version 26.

@lukasj What are your thoughts?

**Comment by lukasj** [comment]
@jmehrens I'm for jumping to API 33+/SE 11 as a base

**Comment by jmehrens** [comment]
Closed as won't fix because Android 7, API 23 is no longer supported.
This issue has been superseded by: https://github.com/jakartaee/mail-api/issues/709
