### ISSUE TITLE
Typo in FactoryFinder error message

### ISSUE THREAD

**Issue by cowwoc** [jakartaee/mail-api#691]
https://github.com/jakartaee/mail-api/blob/29fc0622412712822f27c4303cba4a96aea32100/api/src/main/java/jakarta/mail/util/FactoryFinder.java#L61 looks like a typo to me. Don't you mean to say "No provider of" instead of "Not provider of"?

**Comment by s1ny1998** [comment]
Hey @cowwoc I found this very unpleasant too, planning to raise a PR for all typos regarding this.

**Comment by lukasj** [comment]
this seems to be fixed already by @jmehrens

**Comment by jmehrens** [comment]
Fixed in commit: https://github.com/jakartaee/mail-api/blob/dbb0aa15f6d7e2b681e4b8b87665779f1f6730da/api/src/main/java/jakarta/mail/util/FactoryFinder.java#L61

I didn't add this ticket to the changes.txt.
